var com = {
	"qmino":{
		"miredot":{
		},
	},
};
com.qmino.miredot.restApiSource = {
	"projectName":"sample-webapi",
	"projectVersion":"1.0-SNAPSHOT",
	"projectTitle":"sample-webapi-1.0-SNAPSHOT",
	"buildSystem":"maven 3",
	"miredotVersion":"2.0-RC3",
	"miredotRevision":"0829427a0bf5+",
	"jsonDocEnabled":true,
	"jsonDocHidden":false,
	"singlePage":false,
	"hideLogoOnTop":false,
	"dateOfGeneration":"2016-06-18 22:42:38",
	"validLicense":true,
	"licenseErrorMessage":[
		"Build is approved",

	],
	"onlineLicense":true,
	"loginUrl":null,
	"licenseType":"PRO",
	"allowUsageTracking":false,
	"baseUrl":"http://www.example.com",
	"applicationPath":"/api",
	"issuesTabHidden":false,
};

com.qmino.miredot.restApiSource.tos = {
	"org_dieschnittstelle_mobile_samplewebapi_Todo_in":{
		"type":"complex",
		"name":"org_dieschnittstelle_mobile_samplewebapi_Todo_in",
		"content":[
		],
	},
	"org_dieschnittstelle_mobile_samplewebapi_Todo_out":{
		"type":"complex",
		"name":"org_dieschnittstelle_mobile_samplewebapi_Todo_out",
		"content":[
		],
	},
	"org_dieschnittstelle_mobile_samplewebapi_Todo$LatLng_in":{
		"type":"complex",
		"name":"org_dieschnittstelle_mobile_samplewebapi_Todo$LatLng_in",
		"content":[
		],
	},
	"org_dieschnittstelle_mobile_samplewebapi_Todo$LatLng_out":{
		"type":"complex",
		"name":"org_dieschnittstelle_mobile_samplewebapi_Todo$LatLng_out",
		"content":[
		],
	},
	"org_dieschnittstelle_mobile_samplewebapi_Todo$Location_in":{
		"type":"complex",
		"name":"org_dieschnittstelle_mobile_samplewebapi_Todo$Location_in",
		"content":[
		],
	},
	"org_dieschnittstelle_mobile_samplewebapi_Todo$Location_out":{
		"type":"complex",
		"name":"org_dieschnittstelle_mobile_samplewebapi_Todo$Location_out",
		"content":[
		],
	},
	"org_dieschnittstelle_mobile_samplewebapi_User_in":{
		"type":"complex",
		"name":"org_dieschnittstelle_mobile_samplewebapi_User_in",
		"content":[
		],
	},
	"org_dieschnittstelle_mobile_samplewebapi_User_out":{
		"type":"complex",
		"name":"org_dieschnittstelle_mobile_samplewebapi_User_out",
		"content":[
		],
	},
	"org_dieschnittstelle_mobile_samplewebapi_DataItem_in":{
		"type":"complex",
		"name":"org_dieschnittstelle_mobile_samplewebapi_DataItem_in",
		"content":[
		],
	},
	"org_dieschnittstelle_mobile_samplewebapi_DataItem_out":{
		"type":"complex",
		"name":"org_dieschnittstelle_mobile_samplewebapi_DataItem_out",
		"content":[
		],
	},
};
com.qmino.miredot.restApiSource.enums = {
};
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_Todo_in"].content = [
	{
		"name":"id",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"number",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"name",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"location",
		"comment":null,
		"fullComment":null,
		"typeValue":com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_Todo$Location_in"],
		"deprecated":false,
		"required":false,
	},
	{
		"name":"description",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"contacts",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"collection",
			"typeValue":{
				"type":"simple",
				"typeValue":"string",
			},
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"expiry",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"number",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"done",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"boolean",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"favourite",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"boolean",
		},
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_Todo_in"].ordered = false;
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_Todo_in"].comment = null;
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_Todo_out"].content = [
	{
		"name":"id",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"number",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"name",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"location",
		"comment":null,
		"fullComment":null,
		"typeValue":com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_Todo$Location_out"],
		"deprecated":false,
		"required":false,
	},
	{
		"name":"done",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"boolean",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"description",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"contacts",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"collection",
			"typeValue":{
				"type":"simple",
				"typeValue":"string",
			},
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"expiry",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"number",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"favourite",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"boolean",
		},
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_Todo_out"].ordered = false;
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_Todo_out"].comment = null;
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_Todo$LatLng_in"].content = [
	{
		"name":"lat",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"number",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"lng",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"number",
		},
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_Todo$LatLng_in"].ordered = false;
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_Todo$LatLng_in"].comment = null;
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_Todo$LatLng_out"].content = [
	{
		"name":"lat",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"number",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"lng",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"number",
		},
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_Todo$LatLng_out"].ordered = false;
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_Todo$LatLng_out"].comment = null;
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_Todo$Location_in"].content = [
	{
		"name":"name",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"latlng",
		"comment":null,
		"fullComment":null,
		"typeValue":com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_Todo$LatLng_in"],
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_Todo$Location_in"].ordered = false;
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_Todo$Location_in"].comment = null;
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_Todo$Location_out"].content = [
	{
		"name":"name",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"latlng",
		"comment":null,
		"fullComment":null,
		"typeValue":com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_Todo$LatLng_out"],
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_Todo$Location_out"].ordered = false;
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_Todo$Location_out"].comment = null;
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_User_in"].content = [
	{
		"name":"pwd",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"email",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_User_in"].ordered = false;
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_User_in"].comment = null;
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_User_out"].content = [
	{
		"name":"email",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"pwd",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_User_out"].ordered = false;
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_User_out"].comment = null;
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_DataItem_in"].content = [
	{
		"name":"id",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"number",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"name",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"description",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_DataItem_in"].ordered = false;
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_DataItem_in"].comment = null;
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_DataItem_out"].content = [
	{
		"name":"id",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"number",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"name",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"description",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_DataItem_out"].ordered = false;
com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_DataItem_out"].comment = null;
com.qmino.miredot.restApiSource.interfaces = [
	{
		"beschrijving":"",
		"url":"/todos/",
		"http":"POST",
		"title":null,
		"tags":[
			
		],
		"authors":[
			
		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
			"application/json",
		],
		"produces":[
			"application/json",
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_Todo_out"],
			"comment":null,
		},
		"statusCodes":[
		],
		"hash":"1446081252",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
			],
			"QUERY":[
			],
			"BODY":[
				{
					"typeValue":com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_Todo_in"],
					"comment":null,
					"jaxrs":"BODY",
				},
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
	{
		"beschrijving":"",
		"url":"/todos/{itemId}",
		"http":"PUT",
		"title":null,
		"tags":[
			
		],
		"authors":[
			
		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
			"application/json",
		],
		"produces":[
			"application/json",
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_Todo_out"],
			"comment":null,
		},
		"statusCodes":[
		],
		"hash":"1123702331",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
				{
					"name":"itemId",
					"typeValue":{
						"type":"simple",
						"typeValue":"number",
					},
					"comment":null,
					"jaxrs":"PATH",
				},
			],
			"QUERY":[
			],
			"BODY":[
				{
					"typeValue":com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_Todo_in"],
					"comment":null,
					"jaxrs":"BODY",
				},
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
	{
		"beschrijving":"",
		"url":"/dataitems/",
		"http":"GET",
		"title":null,
		"tags":[
			
		],
		"authors":[
			
		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
		],
		"produces":[
			"application/json",
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":{
				"type":"collection",
				"typeValue":com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_DataItem_out"],
			},
			"comment":null,
		},
		"statusCodes":[
		],
		"hash":"1972888004",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
			],
			"QUERY":[
			],
			"BODY":[
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
	{
		"beschrijving":"a kind of highly simplistic authentication implementation",
		"url":"/users/auth",
		"http":"PUT",
		"title":"a kind of highly simplistic authentication implementation",
		"tags":[
			
		],
		"authors":[
			
		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
			"application/json",
		],
		"produces":[
			"application/json",
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":{
				"type":"simple",
				"typeValue":"boolean",
			},
			"comment":null,
		},
		"statusCodes":[
		],
		"hash":"-622412508",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
			],
			"QUERY":[
			],
			"BODY":[
				{
					"typeValue":com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_User_in"],
					"comment":null,
					"jaxrs":"BODY",
				},
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
	{
		"beschrijving":"",
		"url":"/todos/{itemId}",
		"http":"DELETE",
		"title":null,
		"tags":[
			
		],
		"authors":[
			
		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
		],
		"produces":[
			"application/json",
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":{
				"type":"simple",
				"typeValue":"boolean",
			},
			"comment":null,
		},
		"statusCodes":[
		],
		"hash":"-1130467409",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
				{
					"name":"itemId",
					"typeValue":{
						"type":"simple",
						"typeValue":"number",
					},
					"comment":null,
					"jaxrs":"PATH",
				},
			],
			"QUERY":[
			],
			"BODY":[
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
	{
		"beschrijving":"",
		"url":"/dataitems/{itemId}",
		"http":"GET",
		"title":null,
		"tags":[
			
		],
		"authors":[
			
		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
		],
		"produces":[
			"application/json",
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_DataItem_out"],
			"comment":null,
		},
		"statusCodes":[
		],
		"hash":"-527155704",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
				{
					"name":"itemId",
					"typeValue":{
						"type":"simple",
						"typeValue":"number",
					},
					"comment":null,
					"jaxrs":"PATH",
				},
			],
			"QUERY":[
			],
			"BODY":[
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
	{
		"beschrijving":"",
		"url":"/dataitems/",
		"http":"PUT",
		"title":null,
		"tags":[
			
		],
		"authors":[
			
		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
			"application/json",
		],
		"produces":[
			"application/json",
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_DataItem_out"],
			"comment":null,
		},
		"statusCodes":[
		],
		"hash":"1032637664",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
			],
			"QUERY":[
			],
			"BODY":[
				{
					"typeValue":com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_DataItem_in"],
					"comment":null,
					"jaxrs":"BODY",
				},
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
	{
		"beschrijving":"",
		"url":"/dataitems/{itemId}",
		"http":"DELETE",
		"title":null,
		"tags":[
			
		],
		"authors":[
			
		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
		],
		"produces":[
			"application/json",
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":{
				"type":"simple",
				"typeValue":"boolean",
			},
			"comment":null,
		},
		"statusCodes":[
		],
		"hash":"181598301",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
				{
					"name":"itemId",
					"typeValue":{
						"type":"simple",
						"typeValue":"number",
					},
					"comment":null,
					"jaxrs":"PATH",
				},
			],
			"QUERY":[
			],
			"BODY":[
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
	{
		"beschrijving":"",
		"url":"/todos/",
		"http":"GET",
		"title":null,
		"tags":[
			
		],
		"authors":[
			
		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
		],
		"produces":[
			"application/json",
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":{
				"type":"collection",
				"typeValue":com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_Todo_out"],
			},
			"comment":null,
		},
		"statusCodes":[
		],
		"hash":"-103710428",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
			],
			"QUERY":[
			],
			"BODY":[
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
	{
		"beschrijving":"",
		"url":"/todos/{itemId}",
		"http":"GET",
		"title":null,
		"tags":[
			
		],
		"authors":[
			
		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
		],
		"produces":[
			"application/json",
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_Todo_out"],
			"comment":null,
		},
		"statusCodes":[
		],
		"hash":"1108281626",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
				{
					"name":"itemId",
					"typeValue":{
						"type":"simple",
						"typeValue":"number",
					},
					"comment":null,
					"jaxrs":"PATH",
				},
			],
			"QUERY":[
			],
			"BODY":[
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
	{
		"beschrijving":"",
		"url":"/dataitems/",
		"http":"POST",
		"title":null,
		"tags":[
			
		],
		"authors":[
			
		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
			"application/json",
		],
		"produces":[
			"application/json",
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_DataItem_out"],
			"comment":null,
		},
		"statusCodes":[
		],
		"hash":"6815757",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
			],
			"QUERY":[
			],
			"BODY":[
				{
					"typeValue":com.qmino.miredot.restApiSource.tos["org_dieschnittstelle_mobile_samplewebapi_DataItem_in"],
					"comment":null,
					"jaxrs":"BODY",
				},
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
];
com.qmino.miredot.projectWarnings = [
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":"1446081252",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteTodoCRUDOperationsImpl",
		"implementationMethod":"createTodo",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":"1446081252",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteTodoCRUDOperationsImpl",
		"implementationMethod":"createTodo",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":"1446081252",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteTodoCRUDOperationsImpl",
		"implementationMethod":"createTodo",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":"1446081252",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteTodoCRUDOperationsImpl",
		"implementationMethod":"createTodo",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_AUTHORS",
		"description":"No author(s) specified for interface.",
		"failedBuild":"false",
		"interface":"1446081252",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteTodoCRUDOperationsImpl",
		"implementationMethod":"createTodo",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":"1123702331",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteTodoCRUDOperationsImpl",
		"implementationMethod":"updateTodo",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":"1123702331",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteTodoCRUDOperationsImpl",
		"implementationMethod":"updateTodo",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":"1123702331",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteTodoCRUDOperationsImpl",
		"implementationMethod":"updateTodo",
		"entity":"itemId",
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":"1123702331",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteTodoCRUDOperationsImpl",
		"implementationMethod":"updateTodo",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":"1123702331",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteTodoCRUDOperationsImpl",
		"implementationMethod":"updateTodo",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_AUTHORS",
		"description":"No author(s) specified for interface.",
		"failedBuild":"false",
		"interface":"1123702331",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteTodoCRUDOperationsImpl",
		"implementationMethod":"updateTodo",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":"1972888004",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteDataItemCRUDOperationsImpl",
		"implementationMethod":"readAllDataItems",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":"1972888004",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteDataItemCRUDOperationsImpl",
		"implementationMethod":"readAllDataItems",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":"1972888004",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteDataItemCRUDOperationsImpl",
		"implementationMethod":"readAllDataItems",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_AUTHORS",
		"description":"No author(s) specified for interface.",
		"failedBuild":"false",
		"interface":"1972888004",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteDataItemCRUDOperationsImpl",
		"implementationMethod":"readAllDataItems",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":"-622412508",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteUserOperationsImpl",
		"implementationMethod":"authenticateUser",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":"-622412508",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteUserOperationsImpl",
		"implementationMethod":"authenticateUser",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_AUTHORS",
		"description":"No author(s) specified for interface.",
		"failedBuild":"false",
		"interface":"-622412508",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteUserOperationsImpl",
		"implementationMethod":"authenticateUser",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":"-1130467409",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteTodoCRUDOperationsImpl",
		"implementationMethod":"deleteTodo",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":"-1130467409",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteTodoCRUDOperationsImpl",
		"implementationMethod":"deleteTodo",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":"-1130467409",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteTodoCRUDOperationsImpl",
		"implementationMethod":"deleteTodo",
		"entity":"itemId",
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":"-1130467409",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteTodoCRUDOperationsImpl",
		"implementationMethod":"deleteTodo",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_AUTHORS",
		"description":"No author(s) specified for interface.",
		"failedBuild":"false",
		"interface":"-1130467409",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteTodoCRUDOperationsImpl",
		"implementationMethod":"deleteTodo",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":"-527155704",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteDataItemCRUDOperationsImpl",
		"implementationMethod":"readDataItem",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":"-527155704",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteDataItemCRUDOperationsImpl",
		"implementationMethod":"readDataItem",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":"-527155704",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteDataItemCRUDOperationsImpl",
		"implementationMethod":"readDataItem",
		"entity":"itemId",
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":"-527155704",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteDataItemCRUDOperationsImpl",
		"implementationMethod":"readDataItem",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_AUTHORS",
		"description":"No author(s) specified for interface.",
		"failedBuild":"false",
		"interface":"-527155704",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteDataItemCRUDOperationsImpl",
		"implementationMethod":"readDataItem",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":"1032637664",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteDataItemCRUDOperationsImpl",
		"implementationMethod":"updateDataItem",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":"1032637664",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteDataItemCRUDOperationsImpl",
		"implementationMethod":"updateDataItem",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":"1032637664",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteDataItemCRUDOperationsImpl",
		"implementationMethod":"updateDataItem",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":"1032637664",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteDataItemCRUDOperationsImpl",
		"implementationMethod":"updateDataItem",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_AUTHORS",
		"description":"No author(s) specified for interface.",
		"failedBuild":"false",
		"interface":"1032637664",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteDataItemCRUDOperationsImpl",
		"implementationMethod":"updateDataItem",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":"181598301",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteDataItemCRUDOperationsImpl",
		"implementationMethod":"deleteDataItem",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":"181598301",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteDataItemCRUDOperationsImpl",
		"implementationMethod":"deleteDataItem",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":"181598301",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteDataItemCRUDOperationsImpl",
		"implementationMethod":"deleteDataItem",
		"entity":"itemId",
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":"181598301",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteDataItemCRUDOperationsImpl",
		"implementationMethod":"deleteDataItem",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_AUTHORS",
		"description":"No author(s) specified for interface.",
		"failedBuild":"false",
		"interface":"181598301",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteDataItemCRUDOperationsImpl",
		"implementationMethod":"deleteDataItem",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":"-103710428",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteTodoCRUDOperationsImpl",
		"implementationMethod":"readAllTodos",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":"-103710428",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteTodoCRUDOperationsImpl",
		"implementationMethod":"readAllTodos",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":"-103710428",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteTodoCRUDOperationsImpl",
		"implementationMethod":"readAllTodos",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_AUTHORS",
		"description":"No author(s) specified for interface.",
		"failedBuild":"false",
		"interface":"-103710428",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteTodoCRUDOperationsImpl",
		"implementationMethod":"readAllTodos",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":"1108281626",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteTodoCRUDOperationsImpl",
		"implementationMethod":"readTodo",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":"1108281626",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteTodoCRUDOperationsImpl",
		"implementationMethod":"readTodo",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":"1108281626",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteTodoCRUDOperationsImpl",
		"implementationMethod":"readTodo",
		"entity":"itemId",
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":"1108281626",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteTodoCRUDOperationsImpl",
		"implementationMethod":"readTodo",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_AUTHORS",
		"description":"No author(s) specified for interface.",
		"failedBuild":"false",
		"interface":"1108281626",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteTodoCRUDOperationsImpl",
		"implementationMethod":"readTodo",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":"6815757",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteDataItemCRUDOperationsImpl",
		"implementationMethod":"createDataItem",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":"6815757",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteDataItemCRUDOperationsImpl",
		"implementationMethod":"createDataItem",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":"6815757",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteDataItemCRUDOperationsImpl",
		"implementationMethod":"createDataItem",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":"6815757",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteDataItemCRUDOperationsImpl",
		"implementationMethod":"createDataItem",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_AUTHORS",
		"description":"No author(s) specified for interface.",
		"failedBuild":"false",
		"interface":"6815757",
		"implementationClass":"org.dieschnittstelle.mobile.samplewebapi.impl.RemoteDataItemCRUDOperationsImpl",
		"implementationMethod":"createDataItem",
		"entity":null,
	},
];
com.qmino.miredot.processErrors = [
];
var customHttpMethods = [
];

